name = "SystemsIdentification.jl"
uuid = "6384d8f8-e787-41bd-bb08-3df48ab106b5"
authors = ["Rahul Manavalan"]
version = "0.1.0"

[compat]
julia = "1"

[extras]
Test = "8dfed614-e22c-5e08-85e1-65c5234f0b40"

[targets]
test = ["Test"]
